### ISSUE TITLE
NGinX by default doesn't have permissions to serve content

### ISSUE THREAD

**Issue by VanDavv** [golemfactory/dapp-runner#63] opened 2022-11-22 11:11 UTC
Due to the current limitations, NGinX won't have access to the filesystem to serve the files correctly and will return 404 when accessing correct path.

Working workaround for this situation is to run `/bin/chmod a+x /` before the nginx starts but we are in need of more elegant solution as it will be hard for users to guess how to handle that issue.

**Comment by mateuszsrebrny** [comment] 2022-11-22 11:19
(Core) (meta for the future, no quick workaround)

**Comment by lucekdudek** [comment] 2023-01-19 11:00
@VanDavv do we have any update on this from Core?

**Comment by shadeofblue** [comment] 2023-01-30 09:55
to be analyzed within: https://github.com/golemfactory/yagna-sdk-team/issues/205

**Comment by shadeofblue** [comment] 2023-01-30 10:56
closing as a duplicate of: https://github.com/golemfactory/yagna-sdk-team/issues/205

**Closed by shadeofblue** 2023-01-30 10:56 UTC
Labels: bug, demo-feedback, blocked
